apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=  # Base64 encoded 'admin'
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4tcGFzc3dvcmQ=  # Base64 encoded 'admin-password'

